/** 사용자-facing 카피 — 환영과 정성, Apple 감성의 따뜻한 톤 */

import { GLANGO } from "@/lib/brand/glango";

export const copy = {
  brand: {
    name: GLANGO.name,
    nameKo: GLANGO.nameKo,
    lockup: GLANGO.lockup,
    tagline: GLANGO.tagline,
  },
  nav: {
    feed: "나의 링크",
    inbox: "열린 링크",
    room: "함께하기",
    settings: "설정",
    start: "시작하기",
  },
  feed: {
    title: "나의 링크",
    subtitle: "차곡차곡 모아 둔 링크 · 넘기며 살펴보세요",
    newLinkSaved: "저장되었습니다",
    undoDelete: "삭제되었습니다",
    undo: "되돌리기",
    emptyPaste: "링크 붙여넣기",
    emptyShareHint: "다른 앱에서 글랑고로 공유해도 바로 쌓여요",
    swipeToRoom: "왼쪽으로 밀면 함께하기에 추가",
    linkAddPill: "링크 추가",
    capturePill: "담기",
    remotePill: "리모컨",
    captureSheetTitle: "링크 · 사진 담기",
    captureSheetHint: "URL 붙여넣기 또는 스크린샷을 고르면 바로 액션으로 바꿔 드려요",
    capturePaymentCamera: "📷 계좌 촬영 → 송금",
    capturePaymentFound: "계좌번호를 찾았어요 — 송금 리모컨이 준비됐어요",
    captureIntentFound: "사진 분석 중 — 카드에 가게 정보가 뜰 거예요",
    captureCamera: "📷 사진 찍기",
    captureCameraHint: "메뉴·상품·영수증·명함·티켓·WiFi 등 자동 인식",
    captureOr: "또는",
    screenshotPick: "앨범에서 스크린샷 선택",
    screenshotProcessing: "글자 읽는 중…",
    screenshotFailed: "사진에서 내용을 읽지 못했어요",
    screenshotNoIntent: "가게 이름이나 상품명을 찾지 못했어요 · 더 선명한 캡처를 써 보세요",
    screenshotInvalid: "이미지 파일만 선택할 수 있어요",
    screenshotConfirmPrompt: (query: string) => `「${query}」 맞아요?`,
    screenshotConfirmYes: "맞아요",
    screenshotConfirmRetry: "다시 고르기",
    linkAddLow: "링크 2~3개만 더 쌓으면 더 재밌어요",
    linkAddSingle: "첫 링크예요 · 더 쌓을수록 추천이 맞춰져요",
    linkAddEnd: "끝까지 봤어요 · 링크를 더 추가해 보세요",
    linkAddRecentEmpty: "최근 7일 링크가 없어요 · 새 링크를 추가해 보세요",
    linkAddPaste: "링크 붙여넣기 →",
  },
  inbox: {
    title: "열린 링크",
    subtitle: "링크를 붙여넣어 주세요. 바로 정리해 드릴게요",
    paste: "링크 붙여넣기",
    pastePlaceholder: "링크를 붙여넣어 주세요",
    pasteSubhint: "여러 개는 줄마다",
    select: "선택",
    cancelSelect: "취소",
    selectAll: "전체 선택",
    selectedCount: (n: number) => `${n}개 선택됨`,
    sendBulk: (n: number) => `${n}개 보내기`,
    sendFiltered: (n: number) => `목록 ${n}개 한 번에 보내기`,
    sendToRoom: "함께하기에 추가",
    bulkCopied: "공유 문구를 복사했습니다",
    bulkShared: (n: number) => `${n}개를 보냈습니다`,
    bulkRoomAdded: (n: number, room: string) =>
      `${room}에 링크 ${n}개를 추가했습니다`,
    multiSaved: (n: number) => `링크 ${n}개를 저장했습니다`,
    invalidFormat: "링크 형식을 확인해 주세요",
    alreadyExists: "이미 저장된 링크입니다",
    clipboardUnsupported: "이 브라우저에서는 붙여넣기를 지원하지 않습니다",
    clipboardEmpty: "클립보드가 비어 있습니다",
    clipboardPermission: "붙여넣기 권한이 필요합니다",
    emptyTitle: "아직 저장된 링크가 없습니다",
    emptyHint: `위에 링크를 붙여넣거나, 다른 앱에서 ${GLANGO.name}으로 공유해 주세요`,
    emptyCategory: "이 카테고리에 링크가 없습니다",
    hintInteraction:
      "탭하면 바로 열기 · 길게 누르면 여러 개 선택 · 선택 후 원하는 곳으로 옮겨 드립니다",
    selectPrompt: "옮길 링크를 선택해 주세요",
    openSelected: "열기",
    moveToFeed: "피드",
    savedLabel: "저장됨",
    openLinksCount: (n: number) => `열린 링크 ${n}개`,
    clearedToday: (n: number) => ` · 오늘 ${n}개 마무리`,
    archiveLink: (n: number) => `보관함 ${n}개`,
  },
  burner: {
    work: "일",
    health: "건강",
    friends: "관계",
    growth: "성장",
  },
  coaching: {
    openMany: (n: number) =>
      `열린 링크 ${n}개 — 하나만 마무리해도 훨씬 가벼워집니다`,
    workEvening: (pct: number, growthLabel: string) =>
      `오늘 일 ${pct}% — ${growthLabel} 링크는 내일 아침으로 미뤄도 괜찮아요`,
    workDay: (pct: number) =>
      `일 ${pct}% — 가장 가벼운 것부터 차근차근 시작해 보세요`,
    growthEvening: (growthLabel: string) =>
      `저녁 ${growthLabel} 시간 — AI 요약으로 가볍게 마무리해 보세요`,
    balanced: (a: string, b: string, need: string) =>
      `${a}·${b}가 비슷해요 — ${need}에 맞는 것부터 시작해 주세요`,
    dominant: (burner: string, pct: number, psyche: string) =>
      `${burner} ${pct}% · ${psyche}`,
  },
  room: {
    hubTitle: "함께하기",
    hubSubtitle: "함께 볼 링크 · 1인 1방",
    pageSubtitle: "함께 볼 링크",
    live: "지금 함께 보는 중",
    connecting: "연결 중…",
    emptyTitle: "아직 링크가 없습니다",
    emptyHint: "피드에서 ← 밀거나 공유 → 함께하기에 추가해 보세요",
    roomLimitHint: "방은 1개만 · 피드에서 ← 밀어 추가",
    statusOpen: "아직 남아 있어요",
    statusDone: "완료",
    doneButton: "완료",
    doneToast: "완료되었습니다",
    doneToastHint: "함께하는 분들에게도 표시됩니다",
    crownLabel: (name: string, isSelf: boolean) =>
      isSelf ? "오늘의 MVP는 바로 나" : `${name}님이 MVP`,
    inviteTitle: "함께하기 초대",
    pickerTitle: "어느 방에 추가할까요?",
    pickerHint: "탭하면 바로 들어갑니다",
    createAndAdd: "새 방 만들고 추가",
    linkRoomLive: "함께하기 · 실시간",
    countOpen: (n: number, done: number) =>
      `${n}개 남음 · ${done}개 완료`,
    dockDone: "완료",
    dockComment: "댓글",
    dockSimilar: "비슷한",
    dockSpark: "상상",
    addedToRoomHint: (room: string) => `${room}에 추가됨 · 피드는 이어서 볼 수 있어요`,
    addedToRoom: "함께하기에 추가되었습니다",
    createFail: "방을 만들지 못했습니다. 잠시 후 다시 시도해 주세요",
    openRoom: "방 열기",
    roomNamePlaceholder: "방 이름 (예: 주말 여행)",
    roomNamePlaceholderShort: "예: 제주 여행, 팀 프로젝트",
    friendRoomsTitle: "친구 방",
    friendSendTitle: "어느 방으로 보낼까요?",
    friendSendHint: "추가된 친구 방을 고르거나, 방 주소를 붙여넣어 주세요",
    friendRoomLabel: "친구 방",
    friendRoomsEmpty: "아직 친구 방이 없어요. 아래에 초대 주소를 붙여넣어 주세요",
    friendRoomUrlPlaceholder: "예: https://glango.app/r/주말여행-ab12",
    friendRoomUrlSend: "주소로 보내기",
    friendRoomAdded: "친구 방이 추가되었습니다",
    friendRoomSent: (room: string) => `「${room}」에 보냈습니다`,
    friendRoomSentHint: "잠시 후 상대방 방에서 확인할 수 있습니다",
    friendRoomInvalidUrl: "방 주소 형식을 확인해 주세요",
    friendRoomSame: "지금 보고 있는 방이에요",
    friendRoomSendFail: "링크를 보내지 못했습니다. 잠시 후 다시 시도해 주세요",
    dockSendFriend: "친구 방",
    phaseMap: "방이 지금 길찾기 모드예요",
    phaseCommerce: "방이 지금 쇼핑·가격 비교 모드예요",
    phaseTravel: "방이 지금 여행·예약 모드예요",
    phaseMedia: "방이 지금 영상·재생 모드예요",
    phaseSocial: "방이 지금 공유·문의 모드예요",
    phaseResearch: "방이 지금 검색·요약 모드예요",
  },
  beam: {
    brand: GLANGO.lockup,
    loading: "불러오는 중…",
    notFound: "링크를 찾을 수 없습니다",
    hint: "주소를 찾을 필요 없어요. 아래 버튼만 눌러 주세요",
    copied: "복사되었습니다",
    saveToPocket: "나의 링크에 저장",
    savedToPocket: "열린 링크에 저장되었습니다",
    alreadyInPocket: "이미 저장되어 있습니다",
    pocketHint: "나중에 보려면 한 번만 눌러 주세요",
    openInbox: "열린 링크에서 보기",
  },
  share: {
    beamCopied: "공유 문구를 복사했습니다",
    sent: (label: string) => `${label}(으)로 보냈습니다`,
    pasteHint: "붙여넣기만 하면 바로 열 수 있습니다",
    pasteOnly: "붙여넣기만 하면 됩니다",
    retry: "잠시 후 다시 시도해 주세요",
    honeycombHint: "탭하면 복사되고 앱이 열립니다",
    otherWays: "다른 방법",
    roomInFeed: "함께하기에 추가",
    roomCollab: "함께하기",
    beamShare: "다른 앱으로 보내기",
    directShare: "친구에게 보내기",
    footnote:
      "혼자 볼 링크는 나의 링크, 함께 볼 링크는 함께하기 — 편하게 나눠 두었습니다",
  },
  auth: {
    googleLogin: "Google로 시작하기",
    googleContinue: "Google로 계속하기",
    loggedInAs: (name: string) =>
      `${name}님, 반갑습니다. 나의 링크가 이 계정과 함께합니다`,
    loginHint:
      "기기를 바꿔도 링크를 이어 받고 싶을 때 로그인해 주세요. 로그인 없이도 편하게 쓰실 수 있습니다",
    checking: "로그인 상태를 확인하는 중…",
    logout: "로그아웃",
    logoutOk: "다음에 또 만나요",
    loginFail: "로그인에 실패했습니다",
    loginFailHint: "잠시 후 다시 시도해 주세요",
    loginIncomplete: "로그인이 중단되었습니다",
    devSetupTitle: "로그인 준비 중",
    devSetupHint: "서버 연결이 완료되면 Google로 바로 시작하실 수 있습니다",
    logoutFail: "로그아웃에 실패했습니다. 잠시 후 다시 시도해 주세요",
    guestName: "손님",
    signedInTitle: "로그인되었습니다",
  },
  sync: {
    title: "나의 링크 옮기기",
    hint: `다른 기기의 ${GLANGO.name}에서도 그대로 이어 받으실 수 있습니다`,
    export: "내보내기",
    import: "가져오기",
    exportShared: "파일로 공유했습니다",
    exportCopied: "복사되었습니다 — 다른 기기에 붙여넣어 주세요",
    exportDownload: "파일을 받았습니다",
    importOk: (n: number) => `링크 ${n}개를 다시 모았습니다`,
    importFail: "가져오기에 실패했습니다",
    importFailHint: `${GLANGO.name}에서 만든 백업 파일인지 확인해 주세요`,
  },
  settings: {
    profileTitle: "함께하기 프로필",
    profileHint: "색 뽑기로 정해진 나만의 글랑고 · 홈 아이콘과 연동",
    profileNameLabel: "이름",
    profileNamePlaceholder: "예: 링크 모으는 민지",
    profileAvatarLabel: "내 글랑고",
    profileAvatarFixed: "색은 바꿀 수 없어요 · 처음 배정 그대로",
    profileRarePurple: "✨ 희귀 보라 글랑고 · 100명 중 1명",
    profileRareGranted: "보라 글랑고 당첨! ✨ 운명 수정 완료",
    profileSaved: "프로필을 저장했습니다",
    oddsTitle: "글랑고 색 뽑기 확률",
    oddsHint: "처음 들어올 때 딱 한 번 · 색은 평생 고정",
    oddsBadge: "1회 한정",
    oddsMine: "내꺼",
    oddsUltraRare: "100명 중 1명",
    oddsFooter: "보라는 브랜드 원본 👑 · 다시 뽑기는 없어요 (진짜로)",
    oddsScrollHint: "↓ 손가락으로 내려 전체 확률 보기",
    drawEyebrow: "1회 한정",
    drawTitle: "나만의 글랑고 색 뽑기",
    drawHint: "딱 한 번만! 뽑힌 색은 평생 고정 · 홈 아이콘과 프로필에 바로 반영돼요",
    drawButton: "두근두근! 색 뽑기 🎲",
    drawButtonRolling: "뽑는 중… 두근두근",
    drawRolling: "두근두근… 어떤 색일까?",
    drawIdleCaption: "버튼을 누르면 색이 정해져요",
    drawDoneLabel: "내 글랑고 확정!",
    drawDoneHint: "홈 아이콘과 프로필에 이 색이 적용됐어요",
    drawReveal: (color: string, emoji: string) => `${emoji} ${color} 글랑고 당첨!`,
    drawRevealPurple: "👑 보라 글랑고! 100명 중 1명 · 운명의 색",
    drawResetOk: "처음부터 다시! 이제 색을 뽑아보세요 🎲",
    drawFeedBannerTitle: "아직 글랑고 색을 안 뽑았어요",
    drawFeedBannerHint: "한 번만 뽑으면 홈 아이콘과 프로필에 반영돼요",
    drawFeedBannerCta: "뽑기",
    drawPurpleRevealEyebrow: "울트라레어",
    drawPurpleRevealTitle: "보라 글랑고!",
    drawPurpleRevealBody: "브랜드 원본 색 · 평생 고정 · 진짜 운명이에요",
    drawPurpleRevealOdds: "👑 100명 중 1명만 받는 색",
    drawPurpleRevealDismiss: "멋져요! ✨",
    drawPendingProfile: "아직 색을 뽑지 않았어요 · 위에서 먼저 뽑기!",
    oddsPending: "색을 뽑으면 내 확률표에 ✓ 표시가 생겨요",
    tasteTitle: "추천 취향",
    tasteHint: (max: number) =>
      `링크에 맞는 행동 버튼을 고를 때 참고해요 · 최대 ${max}개`,
    tasteSaved: "추천 취향을 반영했습니다",
    tasteAuto: "자동 추천으로 돌아갔습니다",
    tasteAutoHint: "선택 없음 — 저장한 링크 패턴으로 자동 추천",
    tasteActive: (labels: string) => `우선: ${labels}`,
    scheduleTitle: "실행 예약 매체",
    scheduleHint: "기본값 · 예약할 때마다 카드마다 바꿀 수 있어요",
    scheduleBadge: "기본값",
    scheduleSaved: "실행 예약 매체를 저장했습니다",
    schedulePwaHint: "홈 화면에 추가하면 알림이 더 잘 와요",
    scheduleActive: (label: string) => `지금 기본: ${label}`,
    scheduleSheetTitle: "어디에 저장할까요?",
    scheduleSheetHint: (actionLabel: string) =>
      `${actionLabel} · 이번 카드만 선택`,
    scheduleSheetFootnote: "설정에서 기본값을 바꿀 수 있어요",
    trustTitle: "내 글랑고 레벨",
    trustHint: "익숙해질수록 확인은 줄고 실행은 빨라져요 · 언제든 바꿀 수 있어요",
    trustBadge: "적응형",
    trustSaved: "글랑고 레벨을 저장했습니다",
    trustStageActive: (stage: string) => `지금 단계: ${stage}`,
    trustScoreLine: (score: number) => `성공 경험 ${score}회`,
    trustNextMilestone: (remaining: number, label: string) =>
      `${remaining}회 더하면 ${label}`,
    trustActive: (label: string) => `선택: ${label}`,
    mapSheetTitle: "어떤 지도로 열까요?",
    mapSheetHint: (place: string) => `${place} · 앱을 골라 주세요`,
    mapBadge: "기본값",
    mapSheetFootnote: "다음부터는 기본 지도로 바로 열어요",
    navSectorTitle: "어디로 갈까요?",
    navSectorHint: (place: string) => `${place} · 내비 앱을 골라 주세요`,
    navSectorFootnote: "자주 쓰는 앱이 위로 올라가요 · 안 쓰는 앱은 점점 숨겨져요",
    navSectorFrequentBadge: "자주 씀",
    navSectorHide: "숨기기",
  },
  welcome: {
    headline: "환영합니다",
    body: `카톡·브라우저에서 받은 주소를 ${GLANGO.name}이 `,
    bodyStrong: "지금 할 일",
    bodyEnd: "로 정리해 드립니다",
    pwaOk: "앱처럼 실행 중입니다",
    privacyTitle: "개인정보 · 링크 분석",
    privacyBody:
      "제목·이미지·버튼을 만들기 위해 공유하신 주소만 살짝 살펴봅니다. 로그인 없이도 이용하실 수 있고, 나의 링크는 이 기기에 남습니다",
    privacyLoginNote: "Google로 시작하시면 나의 링크가 계정과 함께합니다",
    privacyLink: "개인정보 안내",
    openFeed: "나의 링크 열기",
    addLink: "링크 추가하기",
    androidSection: "Android · 공유로 추가하기",
    androidStep1Title: `${GLANGO.name} 설치`,
    androidStep1Body: "Chrome 메뉴 → 홈 화면에 추가 또는 아래 설치 버튼",
    androidStep2Title: "다른 앱에서 공유",
    androidStep2Body: (brand: string) =>
      `YouTube·카톡 등 → 공유 → ${brand} 선택`,
    androidStep3Title: "넘기며 보기",
    androidStep3Body:
      "피드에서 위아래로 넘기고, ← 밀면 함께하기 · → 밀면 삭제 (3초 안 되돌리기)",
    iosSection: "iPhone · 붙여넣기로 추가하기",
    iosStep1Title: "홈 화면에 추가",
    iosStep1Body: "Safari 공유 → 홈 화면에 추가",
    iosStep2Title: "링크 복사",
    iosStep2Body: "카톡·Safari에서 링크 복사",
    iosStep3Body: "에 붙여넣기 → 바로 정리해 드립니다",
    desktopSection: "데스크톱",
    desktopMid: "에 링크를 붙여넣거나",
    desktopEnd: "로 먼저 둘러보세요",
    tryDemo: "체험하기",
  },
  comments: {
    done: "완료",
    coupon: "쿠폰",
    note: "메모",
    chat: "말하기",
    couponPreset: "할인 쿠폰 여기 있습니다",
    notePreset: "이것도 참고해 보세요",
    priceSnap: "가격 스냅",
    priceOk: "괜찮아요",
    priceHigh: "다소 비싸요",
  },
  priceVote: {
    title: "이 가격, 어떻게 생각하세요?",
    hintWithPrice: (price: string) => `지금 ${price} — 함께 확인해 보세요`,
    hintNoPrice: "가격 스냅을 찍고 👍👎로 의견을 남겨 주세요",
    snapButton: "가격 스냅",
    okButton: "괜찮아요",
    highButton: "다소 비싸요",
    okMessage: "이 가격은 괜찮은 것 같아요",
    highMessage: "조금 비싼 것 같아요",
    snapSaved: "가격 스냅을 저장했습니다",
    noPriceHint: "제목에서 가격을 찾지 못했습니다 — 메모로 남겨 주세요",
    inlineTitle: (price: string) => `${price}, 이 가격 어떠세요?`,
    inlineTitleFallback: "가격 함께 보기",
  },
  nextLink: {
    title: "다음은 이 링크는 어떠세요?",
    open: "열기",
    roomDone: "다음 링크로 넘어갑니다",
  },
  behavior: {
    doneButton: "완료",
    doneRelease: "하나 마무리하셨습니다",
    doneReleaseHint: "오늘 완료 목록에 추가되었습니다",
    foggCopied: (text: string) => `"${text}" 복사 — 바로 실행하세요`,
  },
  remind: {
    scheduled: (when: string) => `${when}에 다시 알려 드릴게요`,
    calendarOpened: (when: string) => `${when} · Google Calendar에서 저장해 주세요`,
    copiedSchedule: (when: string) => `${when} 예약 문구를 복사했어요`,
    kakaoCopied: "카카오톡에 붙여넣을 문구를 복사했습니다",
  },
  actions: {
    openOriginal: "원본 페이지 열기",
    openLink: "열기",
    referenceLink: "참고 링크 열기",
    translateRead: "번역해서 읽기",
    summary3: "3줄 요약",
    askAi: "AI에게 물어보기",
  },
  routing: {
    fallbackPrompt: "어떤 액션을 원하시나요?",
    fallbackHint: "선택",
    modeCommerce: "쇼핑·최저가",
    modeNews: "뉴스·요약",
    modeOpen: "그냥 열기",
  },
  archive: {
    subtitle: "잠시 쉬어 가는 링크",
  },
  app: {
    tagline: GLANGO.tagline,
    loadingTitle: "잠시만 기다려 주세요",
    loadingSubtitle: "링크에서 할 일을 찾는 중…",
  },
  common: {
    close: "닫기",
    more: "더 보기",
    me: "나",
    tryAgain: "다시 시도해 주세요",
  },
};

export function openOriginalLabel() {
  return copy.actions.openOriginal;
}
