import type { IntentLibraryEntry } from "@/lib/intent-engine/types";

/**
 * Intent Library — standard meaning map.
 * Cues only identify library rows; execution never reads cues directly.
 */
export const INTENT_LIBRARY: readonly IntentLibraryEntry[] = [
  {
    id: "travel.honeymoon",
    category: "Travel",
    labelKo: "신혼여행",
    cues: [/(?:신혼\s*여행|신혼여행|허니문|honeymoon)/iu],
    moods: ["Romantic", "Photography"],
    styles: ["privacy", "photo", "night_view", "relaxed_pace"],
    profile: {
      romantic: 0.95,
      privacy: 0.9,
      budget: "medium_high",
      photo: 0.8,
      pace_relaxed: 0.75,
      shopping: 0.4,
      night_view: 0.7,
    },
    constraints: ["prefer_privacy"],
    priorities: ["atmosphere", "photo", "pace"],
    missingWhenAlone: ["destination", "dates"],
    followUpsWhenAlone: ["어디로 가실 예정인가요?"],
  },
  {
    id: "travel.couple",
    category: "Travel",
    labelKo: "연인여행",
    cues: [/(?:연인|커플|남친|여친|둘이서|둘만의)/iu],
    moods: ["Romantic"],
    styles: ["privacy", "photo"],
    profile: {
      romantic: 0.85,
      privacy: 0.8,
      photo: 0.65,
      pace_relaxed: 0.6,
      budget: "medium",
    },
    priorities: ["atmosphere"],
  },
  {
    id: "mood.indie",
    category: "Lifestyle",
    labelKo: "인디감성",
    cues: [
      /(?:인디\s*감성|인디감성|빈티지|필름\s*카메라|골목\s*카페|독립\s*서점|바이닐|레트로\s*감성)/iu,
    ],
    moods: ["Indie", "Local", "Minimal"],
    styles: ["vintage", "film", "local", "cafe", "bookstore", "vinyl", "quiet", "minimal", "creative"],
    profile: {
      local: 0.9,
      cafe: 0.88,
      quiet: 0.75,
      photo: 0.72,
      shopping: 0.55,
      pace_relaxed: 0.7,
      budget: "medium",
    },
    priorities: ["local", "cafe", "creative"],
  },
  {
    id: "travel.family_parents",
    category: "Travel",
    labelKo: "부모님여행",
    cues: [/(?:부모님|엄마|아빠|어머니|아버지).{0,12}(?:여행|모시)/iu, /(?:모시고).{0,8}(?:여행)/iu],
    moods: ["Family"],
    styles: ["family_friendly", "station_access", "relaxed_pace"],
    profile: {
      family: 0.95,
      pace_relaxed: 0.8,
      quiet: 0.55,
      budget: "medium",
    },
    constraints: ["family_accessibility"],
    priorities: ["comfort", "walk_ease"],
  },
  {
    id: "travel.family",
    category: "Travel",
    labelKo: "가족여행",
    cues: [/(?:가족여행|가족\s*여행|아이|아기|유아|초등학생)/iu],
    moods: ["Family"],
    styles: ["family_friendly"],
    profile: {
      family: 0.9,
      pace_relaxed: 0.7,
      budget: "medium",
    },
    priorities: ["comfort"],
  },
  {
    id: "travel.friends",
    category: "Travel",
    labelKo: "친구여행",
    cues: [/(?:친구들(?:이랑|과)?|우정여행|같이\s*가자)/iu],
    moods: ["Adventure", "Nightlife"],
    styles: ["value", "local"],
    profile: {
      local: 0.65,
      shopping: 0.55,
      pace_packed: 0.55,
      budget: "value",
      adventure: 0.6,
    },
    priorities: ["value", "shared"],
  },
  {
    id: "travel.solo",
    category: "Travel",
    labelKo: "혼자여행",
    cues: [/(?:혼자\s*여행|솔플|solo|나홀로\s*여행)/iu],
    moods: ["Local", "Minimal"],
    styles: ["local", "minimal"],
    profile: {
      local: 0.7,
      pace_relaxed: 0.55,
      budget: "medium",
    },
    priorities: ["flexibility"],
  },
  {
    id: "travel.business",
    category: "Work",
    labelKo: "출장",
    cues: [/(?:출장|비즈니스\s*트립|business\s*trip)/iu],
    moods: ["Business"],
    styles: ["station_access", "minimal"],
    profile: {
      business: 0.95,
      pace_packed: 0.7,
      budget: "medium",
      quiet: 0.4,
    },
    constraints: ["near_station_or_venue"],
    priorities: ["access", "time"],
    missingWhenAlone: ["dates", "venue_or_city"],
  },
  {
    id: "mood.relax",
    category: "Lifestyle",
    labelKo: "여유힐링",
    cues: [/(?:느긋|여유|힐링|쉬고\s*싶|천천히)/iu],
    moods: ["Relax"],
    styles: ["quiet", "relaxed_pace"],
    profile: {
      pace_relaxed: 0.9,
      quiet: 0.8,
    },
    priorities: ["pace"],
  },
  {
    id: "mood.luxury",
    category: "Lifestyle",
    labelKo: "럭셔리",
    cues: [/(?:럭셔리|호캉스|프리미엄|고급\s*호텔)/iu],
    moods: ["Luxury"],
    styles: ["premium", "privacy"],
    profile: {
      luxury: 0.9,
      privacy: 0.7,
      budget: "premium",
    },
    priorities: ["quality"],
  },
  {
    id: "mood.photo",
    category: "Lifestyle",
    labelKo: "사진여행",
    cues: [/(?:인생샷|포토\s*스팟|사진\s*여행|필름\s*감성)/iu],
    moods: ["Photography"],
    styles: ["photo", "film"],
    profile: {
      photo: 0.92,
    },
    priorities: ["photo"],
  },
] as const;

export function getIntentLibraryEntry(id: string): IntentLibraryEntry | null {
  return INTENT_LIBRARY.find((row) => row.id === id) ?? null;
}
