export {
  LEGACY_SURFACE_REDIRECTS,
  RIMVIO_DEPRECATED_SURFACES,
  RIMVIO_DEV_ONLY_ROUTES,
  RIMVIO_PRIMARY_SURFACES,
  RIMVIO_REDIRECTS,
  RIMVIO_SECONDARY_SURFACES,
  SURFACE_ROUTES,
  isGlobeHomePath,
  isPrimaryNavGlobePath,
  rimvioBottomNavRoutes,
  type RimvioDeprecatedSurface,
  type RimvioLegacyRedirectFrom,
  type RimvioNavLabelKey,
  type RimvioPrimarySurface,
  type RimvioSecondaryNavLabelKey,
  type RimvioSecondarySurface,
  type RimvioSurfaceId,
} from "./rimvio-surface-ia";
