import type { EntityCatalogEntry } from "@/lib/entity-resolver/catalogs/catalog-types";

/** P1 — Airports (Transit ≠ City). */
export const AIRPORT_CATALOG: readonly EntityCatalogEntry[] = [
  {
    id: "airport:nrt",
    labelKo: "나리타 공항",
    queryKo: "나리타 공항",
    kind: "Airport",
    pattern: /나리타(?:\s*국제공항|\s*공항)?|\bnrt\b|narita(?:\s*airport)?|成田/iu,
    aliases: ["NRT", "Narita", "成田空港"],
    semanticPath: ["Airport", "Transit", "Air"],
    geoId: "geo:jp:nrt",
    confidence: 0.96,
  },
  {
    id: "airport:hnd",
    labelKo: "하네다 공항",
    queryKo: "하네다 공항",
    kind: "Airport",
    pattern: /하네다(?:\s*공항)?|\bhnd\b|haneda(?:\s*airport)?|羽田/iu,
    aliases: ["HND", "Haneda", "羽田空港"],
    semanticPath: ["Airport", "Transit", "Air"],
    geoId: "geo:jp:hnd",
    confidence: 0.96,
  },
  {
    id: "airport:kix",
    labelKo: "간사이 공항",
    queryKo: "간사이 공항",
    kind: "Airport",
    pattern: /간사이(?:\s*국제공항|\s*공항)?|\bkix\b|kansai(?:\s*airport)?|関西空港/iu,
    aliases: ["KIX", "Kansai"],
    semanticPath: ["Airport", "Transit", "Air"],
    geoId: "geo:jp:kix",
    confidence: 0.95,
  },
  {
    id: "airport:icn",
    labelKo: "인천공항",
    queryKo: "인천공항",
    kind: "Airport",
    pattern: /인천(?:국제공항|공항)?|\bicn\b|incheon(?:\s*airport)?/iu,
    aliases: ["ICN", "Incheon"],
    semanticPath: ["Airport", "Transit", "Air"],
    geoId: "geo:kr:icn",
    confidence: 0.96,
  },
  {
    id: "airport:gmp",
    labelKo: "김포공항",
    queryKo: "김포공항",
    kind: "Airport",
    pattern: /김포(?:국제공항|공항)?|\bgmp\b|gimpo(?:\s*airport)?/iu,
    aliases: ["GMP", "Gimpo"],
    semanticPath: ["Airport", "Transit", "Air"],
    geoId: "geo:kr:gmp",
    confidence: 0.95,
  },
];
