import type { EntityCatalogEntry } from "@/lib/entity-resolver/catalogs/catalog-types";

/** P2 — Cafe / beverage chains (not FastFood). */
export const CAFE_CHAIN_CATALOG: readonly EntityCatalogEntry[] = [
  {
    id: "cafe:doutor",
    labelKo: "도토루",
    queryKo: "도토루",
    kind: "Brand",
    pattern: /도토루|doutor|ドトール/iu,
    aliases: ["Doutor", "ドトール"],
    semanticPath: ["Brand", "CafeChain", "Cafe", "Eatery"],
    confidence: 0.94,
  },
  {
    id: "cafe:komeda",
    labelKo: "코메다",
    queryKo: "코메다",
    kind: "Brand",
    pattern: /코메다|komeda|コメダ/iu,
    aliases: ["Komeda", "コメダ珈琲"],
    semanticPath: ["Brand", "CafeChain", "Cafe", "Eatery"],
    confidence: 0.94,
  },
  {
    id: "cafe:bluebottle",
    labelKo: "블루보틀",
    queryKo: "블루보틀",
    kind: "Brand",
    pattern: /블루\s*보틀|blue\s*bottle|ブルーボトル/iu,
    aliases: ["Blue Bottle"],
    semanticPath: ["Brand", "CafeChain", "Cafe", "Eatery"],
    confidence: 0.93,
  },
  {
    id: "cafe:tullys",
    labelKo: "タリーズ",
    queryKo: "タリーズ",
    kind: "Brand",
    pattern: /탈리즈|tully'?s|タリーズ/iu,
    aliases: ["Tully's", "タリーズ"],
    semanticPath: ["Brand", "CafeChain", "Cafe", "Eatery"],
    confidence: 0.92,
  },
  {
    id: "cafe:compose",
    labelKo: "컴포즈커피",
    queryKo: "컴포즈커피",
    kind: "Brand",
    pattern: /컴포즈|compose\s*coffee/iu,
    aliases: ["Compose Coffee"],
    semanticPath: ["Brand", "CafeChain", "Cafe", "Eatery"],
    confidence: 0.92,
  },
  {
    id: "cafe:ediya",
    labelKo: "이디야",
    queryKo: "이디야",
    kind: "Brand",
    pattern: /이디야|ediya/iu,
    aliases: ["Ediya"],
    semanticPath: ["Brand", "CafeChain", "Cafe", "Eatery"],
    confidence: 0.92,
  },
];
