import type { EntityCatalogEntry } from "@/lib/entity-resolver/catalogs/catalog-types";

/** P1 — Landmark / POI (not City). */
export const LANDMARK_CATALOG: readonly EntityCatalogEntry[] = [
  {
    id: "landmark:tokyo-disneyland",
    labelKo: "도쿄 디즈니랜드",
    queryKo: "도쿄 디즈니랜드",
    kind: "Location",
    pattern: /도쿄\s*디즈니(?:랜드)?|tokyo\s*disneyland|東京ディズニーランド/iu,
    aliases: ["disneyland", "디즈니랜드", "東京ディズニーランド"],
    semanticPath: ["Landmark", "ThemePark", "POI", "Location"],
    geoId: "geo:jp:tokyo:disneyland",
    confidence: 0.95,
  },
  {
    id: "landmark:tokyo-disneysea",
    labelKo: "도쿄 디즈니씨",
    queryKo: "도쿄 디즈니씨",
    kind: "Location",
    pattern: /디즈니\s*씨|disney\s*sea|東京ディズニーシー/iu,
    aliases: ["disneysea", "디즈니씨"],
    semanticPath: ["Landmark", "ThemePark", "POI", "Location"],
    geoId: "geo:jp:tokyo:disneysea",
    confidence: 0.95,
  },
  {
    id: "landmark:uso",
    labelKo: "유니버설 스튜디오 재팬",
    queryKo: "유니버설 스튜디오 재팬",
    kind: "Location",
    pattern:
      /유니버설\s*스튜디오|universal\s*studios?\s*(?:japan|osaka)?|\busj\b|ユニバーサル/iu,
    aliases: ["USJ", "ユニバーサル・スタジオ・ジャパン"],
    semanticPath: ["Landmark", "ThemePark", "POI", "Location"],
    geoId: "geo:jp:osaka:usj",
    confidence: 0.95,
  },
  {
    id: "landmark:sensoji",
    labelKo: "센소지",
    queryKo: "센소지",
    kind: "Museum",
    pattern: /센소지|아사쿠사\s*절|senso[- ]?ji|浅草寺/iu,
    aliases: ["Senso-ji", "浅草寺", "아사쿠사 절"],
    semanticPath: ["Landmark", "Temple", "POI", "Location"],
    geoId: "geo:jp:tokyo:sensoji",
    confidence: 0.94,
  },
  {
    id: "landmark:ueno-park",
    labelKo: "우에노 공원",
    queryKo: "우에노 공원",
    kind: "Location",
    pattern: /우에노\s*공원|ueno\s*park|上野公園/iu,
    aliases: ["Ueno Park", "上野公園"],
    semanticPath: ["Landmark", "Park", "POI", "Location"],
    geoId: "geo:jp:tokyo:ueno-park",
    confidence: 0.93,
  },
  {
    id: "landmark:skytree",
    labelKo: "도쿄 스카이트리",
    queryKo: "도쿄 스카이트리",
    kind: "Location",
    pattern: /스카이\s*트리|skytree|東京スカイツリー/iu,
    aliases: ["Tokyo Skytree", "スカイツリー"],
    semanticPath: ["Landmark", "Tower", "POI", "Location"],
    geoId: "geo:jp:tokyo:skytree",
    confidence: 0.94,
  },
  {
    id: "landmark:shibuya-crossing",
    labelKo: "시부야 스크램블",
    queryKo: "시부야 스크램블",
    kind: "Location",
    pattern: /시부야\s*스크램블|shibuya\s*crossing|渋谷スクランブル/iu,
    aliases: ["Shibuya Crossing"],
    semanticPath: ["Landmark", "POI", "Location"],
    geoId: "geo:jp:tokyo:shibuya-crossing",
    confidence: 0.9,
  },
  {
    id: "landmark:teamlab",
    labelKo: "팀랩",
    queryKo: "팀랩",
    kind: "Museum",
    pattern: /팀\s*랩|teamlab|チームラボ/iu,
    aliases: ["teamLab", "チームラボ"],
    semanticPath: ["Landmark", "Museum", "POI", "Location"],
    geoId: "geo:jp:tokyo:teamlab-planets",
    confidence: 0.92,
  },
  {
    id: "landmark:fushimi-inari",
    labelKo: "후시미 이나리",
    queryKo: "후시미 이나리",
    kind: "Location",
    pattern: /후시미\s*이나리|fushimi\s*inari|伏見稲荷/iu,
    aliases: ["Fushimi Inari", "伏見稲荷"],
    semanticPath: ["Landmark", "Temple", "POI", "Location"],
    geoId: "geo:jp:kyoto:fushimi-inari",
    confidence: 0.94,
  },
  {
    id: "landmark:tokyo-tower",
    labelKo: "도쿄타워",
    queryKo: "도쿄타워",
    kind: "Location",
    pattern: /도쿄\s*타워|tokyo\s*tower|東京タワー/iu,
    aliases: ["Tokyo Tower", "東京タワー"],
    semanticPath: ["Landmark", "Tower", "POI", "Location"],
    geoId: "geo:jp:tokyo:tokyo-tower",
    confidence: 0.93,
  },
  {
    id: "landmark:osaka-castle",
    labelKo: "오사카성",
    queryKo: "오사카성",
    kind: "Location",
    pattern: /오사카\s*성|osaka\s*castle|大阪城/iu,
    aliases: ["Osaka Castle", "大阪城"],
    semanticPath: ["Landmark", "Castle", "POI", "Location"],
    geoId: "geo:jp:osaka:osaka-castle",
    confidence: 0.93,
  },
  {
    id: "landmark:n-seoul-tower",
    labelKo: "N서울타워",
    queryKo: "N서울타워",
    kind: "Location",
    pattern: /n\s*서울\s*타워|남산\s*타워|n\s*seoul\s*tower|namsan\s*tower/iu,
    aliases: ["N Seoul Tower", "남산타워"],
    semanticPath: ["Landmark", "Tower", "POI", "Location"],
    geoId: "geo:kr:seoul:n-seoul-tower",
    confidence: 0.93,
  },
  {
    id: "landmark:gyeongbokgung",
    labelKo: "경복궁",
    queryKo: "경복궁",
    kind: "Location",
    pattern: /경복궁|gyeongbokgung|gyeongbok\s*palace/iu,
    aliases: ["Gyeongbokgung"],
    semanticPath: ["Landmark", "Palace", "POI", "Location"],
    geoId: "geo:kr:seoul:gyeongbokgung",
    confidence: 0.94,
  },
  {
    id: "landmark:lotte-world",
    labelKo: "롯데월드",
    queryKo: "롯데월드",
    kind: "Location",
    pattern: /롯데\s*월드|lotte\s*world/iu,
    aliases: ["Lotte World"],
    semanticPath: ["Landmark", "ThemePark", "POI", "Location"],
    geoId: "geo:kr:seoul:lotte-world",
    confidence: 0.93,
  },
];
