import type { EntityCatalogEntry } from "@/lib/entity-resolver/catalogs/catalog-types";

/** P1 — Landmark / POI (not City). */
export const LANDMARK_CATALOG: readonly EntityCatalogEntry[] = [
  {
    id: "landmark:tokyo-disneyland",
    labelKo: "도쿄 디즈니랜드",
    queryKo: "도쿄 디즈니랜드",
    kind: "Location",
    pattern: /도쿄\s*디즈니(?:랜드)?|tokyo\s*disneyland|東京ディズニーランド/iu,
    aliases: ["disneyland", "디즈니랜드", "東京ディズニーランド"],
    semanticPath: ["Landmark", "ThemePark", "POI", "Location"],
    geoId: "geo:jp:tokyo:disneyland",
    confidence: 0.95,
  },
  {
    id: "landmark:tokyo-disneysea",
    labelKo: "도쿄 디즈니씨",
    queryKo: "도쿄 디즈니씨",
    kind: "Location",
    pattern: /디즈니\s*씨|disney\s*sea|東京ディズニーシー/iu,
    aliases: ["disneysea", "디즈니씨"],
    semanticPath: ["Landmark", "ThemePark", "POI", "Location"],
    geoId: "geo:jp:tokyo:disneysea",
    confidence: 0.95,
  },
  {
    id: "landmark:uso",
    labelKo: "유니버설 스튜디오 재팬",
    queryKo: "유니버설 스튜디오 재팬",
    kind: "Location",
    pattern:
      /유니버설\s*스튜디오|universal\s*studios?\s*(?:japan|osaka)?|\busj\b|ユニバーサル/iu,
    aliases: ["USJ", "ユニバーサル・スタジオ・ジャパン"],
    semanticPath: ["Landmark", "ThemePark", "POI", "Location"],
    geoId: "geo:jp:osaka:usj",
    confidence: 0.95,
  },
  {
    id: "landmark:sensoji",
    labelKo: "센소지",
    queryKo: "센소지",
    kind: "Museum",
    pattern: /센소지|아사쿠사\s*절|senso[- ]?ji|浅草寺/iu,
    aliases: ["Senso-ji", "浅草寺", "아사쿠사 절"],
    semanticPath: ["Landmark", "Temple", "POI", "Location"],
    geoId: "geo:jp:tokyo:sensoji",
    confidence: 0.94,
  },
  {
    id: "landmark:ueno-park",
    labelKo: "우에노 공원",
    queryKo: "우에노 공원",
    kind: "Location",
    pattern: /우에노\s*공원|ueno\s*park|上野公園/iu,
    aliases: ["Ueno Park", "上野公園"],
    semanticPath: ["Landmark", "Park", "POI", "Location"],
    geoId: "geo:jp:tokyo:ueno-park",
    confidence: 0.93,
  },
  {
    id: "landmark:skytree",
    labelKo: "도쿄 스카이트리",
    queryKo: "도쿄 스카이트리",
    kind: "Location",
    pattern: /스카이\s*트리|skytree|東京スカイツリー/iu,
    aliases: ["Tokyo Skytree", "スカイツリー"],
    semanticPath: ["Landmark", "Tower", "POI", "Location"],
    geoId: "geo:jp:tokyo:skytree",
    confidence: 0.94,
  },
  {
    id: "landmark:shibuya-crossing",
    labelKo: "시부야 스크램블",
    queryKo: "시부야 스크램블",
    kind: "Location",
    pattern: /시부야\s*스크램블|shibuya\s*crossing|渋谷スクランブル/iu,
    aliases: ["Shibuya Crossing"],
    semanticPath: ["Landmark", "POI", "Location"],
    geoId: "geo:jp:tokyo:shibuya-crossing",
    confidence: 0.9,
  },
  {
    id: "landmark:teamlab",
    labelKo: "팀랩",
    queryKo: "팀랩",
    kind: "Museum",
    pattern: /팀\s*랩|teamlab|チームラボ/iu,
    aliases: ["teamLab", "チームラボ"],
    semanticPath: ["Landmark", "Museum", "POI", "Location"],
    confidence: 0.92,
  },
];
