import type { EntityCatalogEntry } from "@/lib/entity-resolver/catalogs/catalog-types";

/** P1 — Lodging brands / stay types (Eatery Brand의 반대축). */
export const LODGING_BRAND_CATALOG: readonly EntityCatalogEntry[] = [
  {
    id: "lodging:toyoko-inn",
    labelKo: "도요코인",
    queryKo: "도요코인",
    kind: "Hotel",
    pattern: /도요코\s*인|toyoko\s*inn|東横イン/iu,
    aliases: ["Toyoko Inn", "東横イン"],
    semanticPath: ["Brand", "HotelChain", "BusinessHotel", "Lodging"],
    confidence: 0.95,
  },
  {
    id: "lodging:apa",
    labelKo: "APA호텔",
    queryKo: "APA호텔",
    kind: "Hotel",
    pattern: /apa\s*호텔|アパホテル/iu,
    aliases: ["APA Hotel", "アパホテル"],
    semanticPath: ["Brand", "HotelChain", "BusinessHotel", "Lodging"],
    confidence: 0.94,
  },
  {
    id: "lodging:hilton",
    labelKo: "힐튼",
    queryKo: "힐튼",
    kind: "Hotel",
    pattern: /힐튼|hilton/iu,
    aliases: ["Hilton"],
    semanticPath: ["Brand", "HotelChain", "Hotel", "Lodging"],
    confidence: 0.94,
  },
  {
    id: "lodging:marriott",
    labelKo: "메리어트",
    queryKo: "메리어트",
    kind: "Hotel",
    pattern: /메리어트|marriott/iu,
    aliases: ["Marriott"],
    semanticPath: ["Brand", "HotelChain", "Hotel", "Lodging"],
    confidence: 0.94,
  },
  {
    id: "lodging:capsule",
    labelKo: "캡슐호텔",
    queryKo: "캡슐호텔",
    kind: "Hotel",
    pattern: /캡슐\s*호텔|capsule\s*hotel|カプセルホテル/iu,
    aliases: ["capsule hotel", "カプセルホテル"],
    semanticPath: ["StayType", "Capsule", "Lodging"],
    confidence: 0.93,
  },
  {
    id: "lodging:ryokan",
    labelKo: "료칸",
    queryKo: "료칸",
    kind: "Hotel",
    pattern: /료칸|ryokan|旅館/iu,
    aliases: ["ryokan", "旅館"],
    semanticPath: ["StayType", "Ryokan", "Lodging"],
    confidence: 0.93,
  },
  {
    id: "lodging:airbnb",
    labelKo: "에어비앤비",
    queryKo: "에어비앤비",
    kind: "Hotel",
    pattern: /에어비앤비|airbnb|민박/iu,
    aliases: ["Airbnb"],
    semanticPath: ["Brand", "StayType", "Airbnb", "Lodging"],
    confidence: 0.93,
  },
  {
    id: "lodging:hostel",
    labelKo: "호스텔",
    queryKo: "호스텔",
    kind: "Hotel",
    pattern: /호스텔|hostel|게스트\s*하우스/iu,
    aliases: ["hostel", "guesthouse"],
    semanticPath: ["StayType", "Hostel", "Lodging"],
    confidence: 0.9,
  },
];
