import type { EntityCatalogEntry } from "@/lib/entity-resolver/catalogs/catalog-types";

/** P2 — Retail / non-food brands — NEVER Eatery. */
export const RETAIL_BRAND_CATALOG: readonly EntityCatalogEntry[] = [
  {
    id: "retail:uniqlo",
    labelKo: "유니클로",
    queryKo: "유니클로",
    kind: "Brand",
    pattern: /유니클로|uniqlo|ユニクロ/iu,
    aliases: ["Uniqlo", "ユニクロ"],
    semanticPath: ["Brand", "Retail", "Clothing", "Amenity"],
    confidence: 0.95,
  },
  {
    id: "retail:donki",
    labelKo: "돈키호테",
    queryKo: "돈키호테",
    kind: "Brand",
    pattern: /돈키(?:호테)?|donki|don\s*quijote|ドン・?キ/iu,
    aliases: ["Don Quijote", "ドンキ"],
    semanticPath: ["Brand", "Retail", "VarietyStore", "Amenity"],
    confidence: 0.95,
  },
  {
    id: "retail:muji",
    labelKo: "무인양품",
    queryKo: "무인양품",
    kind: "Brand",
    pattern: /무인양품|muji|無印/iu,
    aliases: ["MUJI", "無印良品"],
    semanticPath: ["Brand", "Retail", "Lifestyle", "Amenity"],
    confidence: 0.94,
  },
  {
    id: "retail:bic",
    labelKo: "빅카메라",
    queryKo: "빅카메라",
    kind: "Brand",
    pattern: /빅\s*카메라|bic\s*camera|ビックカメラ/iu,
    aliases: ["Bic Camera"],
    semanticPath: ["Brand", "Retail", "Electronics", "Amenity"],
    confidence: 0.93,
  },
  {
    id: "retail:yodobashi",
    labelKo: "요도바시",
    queryKo: "요도바시",
    kind: "Brand",
    pattern: /요도바시|yodobashi|ヨドバシ/iu,
    aliases: ["Yodobashi"],
    semanticPath: ["Brand", "Retail", "Electronics", "Amenity"],
    confidence: 0.93,
  },
  {
    id: "retail:oliveyoung",
    labelKo: "올리브영",
    queryKo: "올리브영",
    kind: "Brand",
    pattern: /올리브영|olive\s*young/iu,
    aliases: ["Olive Young"],
    semanticPath: ["Brand", "Retail", "Beauty", "Amenity"],
    confidence: 0.93,
  },
];
