import type { EntityCatalogEntry } from "@/lib/entity-resolver/catalogs/catalog-types";

/** P2 — Transport modes / cards (Station 보강). */
export const TRANSPORT_MODE_CATALOG: readonly EntityCatalogEntry[] = [
  {
    id: "transport:jr",
    labelKo: "JR",
    queryKo: "JR",
    kind: "Product",
    pattern: /\bjr\b|제이알|japan\s*rail/iu,
    aliases: ["JR", "Japan Rail"],
    semanticPath: ["Transport", "Rail", "Operator"],
    confidence: 0.9,
  },
  {
    id: "transport:subway",
    labelKo: "지하철",
    queryKo: "지하철",
    kind: "Product",
    pattern: /지하철|metro|subway|メトロ|전철/iu,
    aliases: ["metro", "地下鉄"],
    semanticPath: ["Transport", "Rail", "Subway"],
    confidence: 0.88,
  },
  {
    id: "transport:shinkansen",
    labelKo: "신칸센",
    queryKo: "신칸센",
    kind: "Product",
    pattern: /신칸센|shinkansen|新幹線/iu,
    aliases: ["Shinkansen", "新幹線"],
    semanticPath: ["Transport", "Rail", "Shinkansen"],
    confidence: 0.94,
  },
  {
    id: "transport:suica",
    labelKo: "Suica",
    queryKo: "Suica",
    kind: "Product",
    pattern: /suica|스이카|スイカ/iu,
    aliases: ["Suica", "スイカ"],
    semanticPath: ["Transport", "TransitCard", "Payment"],
    confidence: 0.93,
  },
  {
    id: "transport:pasmo",
    labelKo: "PASMO",
    queryKo: "PASMO",
    kind: "Product",
    pattern: /pasmo|파스모|パスモ/iu,
    aliases: ["PASMO"],
    semanticPath: ["Transport", "TransitCard", "Payment"],
    confidence: 0.93,
  },
  {
    id: "transport:icoca",
    labelKo: "ICOCA",
    queryKo: "ICOCA",
    kind: "Product",
    pattern: /icoca|이코카/iu,
    aliases: ["ICOCA"],
    semanticPath: ["Transport", "TransitCard", "Payment"],
    confidence: 0.92,
  },
];
