/**
 * Frequent JP/KR stations · neighborhoods · landmarks people ask on Globe scout.
 * Compact rows → WorldGeoNode. Expand here (not LLM memory); keep ids stable.
 */
import type { WorldGeoEntityId, WorldGeoNode } from "@/lib/reality-graph/types";

type FrequentGeoRow = {
  readonly id: WorldGeoEntityId;
  readonly kind: WorldGeoNode["kind"];
  readonly parentId: WorldGeoEntityId;
  readonly ko: string;
  readonly en: string;
  readonly local?: string;
  readonly aliases: readonly string[];
  readonly lat: number;
  readonly lng: number;
  readonly tz: string;
  readonly currency: string;
  readonly lang: string;
};

function nodeFromRow(row: FrequentGeoRow): WorldGeoNode {
  return {
    id: row.id,
    kind: row.kind,
    parentId: row.parentId,
    labels: {
      ko: row.ko,
      en: row.en,
      local: row.local,
      aliases: row.aliases,
    },
    centroid: { lat: row.lat, lng: row.lng },
    boundary: null,
    ianaTimeZone: row.tz,
    currencyCode: row.currency,
    primaryLanguage: row.lang,
  };
}

const JP = {
  tz: "Asia/Tokyo",
  currency: "JPY",
  lang: "ja",
} as const;

const KR = {
  tz: "Asia/Seoul",
  currency: "KRW",
  lang: "ko",
} as const;

/** Regions / cities that stations hang under. */
const REGION_ROWS: readonly FrequentGeoRow[] = [
  {
    id: "geo:jp:fukuoka",
    kind: "prefecture",
    parentId: "geo:jp",
    ko: "후쿠오카",
    en: "Fukuoka",
    local: "福岡",
    aliases: ["fukuoka", "후쿠오카", "福岡", "하카타"],
    lat: 33.5904,
    lng: 130.4017,
    ...JP,
  },
  {
    id: "geo:jp:nagoya",
    kind: "city",
    parentId: "geo:jp",
    ko: "나고야",
    en: "Nagoya",
    local: "名古屋",
    aliases: ["nagoya", "나고야", "名古屋"],
    lat: 35.1815,
    lng: 136.9066,
    ...JP,
  },
  {
    id: "geo:jp:nara",
    kind: "prefecture",
    parentId: "geo:jp",
    ko: "나라",
    en: "Nara",
    local: "奈良",
    aliases: ["nara", "나라", "奈良"],
    lat: 34.6851,
    lng: 135.8048,
    ...JP,
  },
  {
    id: "geo:jp:yokohama",
    kind: "city",
    parentId: "geo:jp",
    ko: "요코하마",
    en: "Yokohama",
    local: "横浜",
    aliases: ["yokohama", "요코하마", "横浜"],
    lat: 35.4437,
    lng: 139.638,
    ...JP,
  },
  {
    id: "geo:jp:okinawa",
    kind: "prefecture",
    parentId: "geo:jp",
    ko: "오키나와",
    en: "Okinawa",
    local: "沖縄",
    aliases: ["okinawa", "오키나와", "沖縄", "나하", "naha"],
    lat: 26.2124,
    lng: 127.6809,
    ...JP,
  },
  {
    id: "geo:jp:hokkaido:sapporo",
    kind: "city",
    parentId: "geo:jp:hokkaido",
    ko: "삿포로",
    en: "Sapporo",
    local: "札幌",
    aliases: ["sapporo", "삿포로", "札幌"],
    lat: 43.0618,
    lng: 141.3545,
    ...JP,
  },
  {
    id: "geo:kr:busan",
    kind: "metropolis",
    parentId: "geo:kr",
    ko: "부산",
    en: "Busan",
    local: "부산",
    aliases: ["busan", "부산", "부산광역시", "pusan"],
    lat: 35.1796,
    lng: 129.0756,
    ...KR,
  },
  {
    id: "geo:kr:jeju",
    kind: "prefecture",
    parentId: "geo:kr",
    ko: "제주",
    en: "Jeju",
    local: "제주",
    aliases: ["jeju", "제주", "제주도", "jeju island", "제주특별자치도"],
    lat: 33.4996,
    lng: 126.5312,
    ...KR,
  },
  {
    id: "geo:kr:daejeon",
    kind: "metropolis",
    parentId: "geo:kr",
    ko: "대전",
    en: "Daejeon",
    local: "대전",
    aliases: ["daejeon", "대전", "대전광역시"],
    lat: 36.3504,
    lng: 127.3845,
    ...KR,
  },
];

/**
 * Stations — aliases prefer 「X역」 so bare ward names (신주쿠) keep district hits.
 * Bare area nouns only when no competing admin node.
 */
const STATION_ROWS: readonly FrequentGeoRow[] = [
  // ——— Tokyo ———
  {
    id: "geo:jp:tokyo:shinjuku-station",
    kind: "poi",
    parentId: "geo:jp:tokyo:shinjuku",
    ko: "신주쿠역",
    en: "Shinjuku Station",
    local: "新宿駅",
    aliases: ["신주쿠역", "shinjuku station", "新宿駅", "신주쿠 역"],
    lat: 35.6896,
    lng: 139.7006,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:shibuya-station",
    kind: "poi",
    parentId: "geo:jp:tokyo:shibuya",
    ko: "시부야역",
    en: "Shibuya Station",
    local: "渋谷駅",
    aliases: ["시부야역", "shibuya station", "渋谷駅", "시부야 역"],
    lat: 35.658,
    lng: 139.7016,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:ikebukuro-station",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "이케부쿠로역",
    en: "Ikebukuro Station",
    local: "池袋駅",
    aliases: [
      "이케부쿠로역",
      "이케부쿠로",
      "ikebukuro",
      "ikebukuro station",
      "池袋",
      "池袋駅",
    ],
    lat: 35.7295,
    lng: 139.7109,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:ueno-station",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "우에노역",
    en: "Ueno Station",
    local: "上野駅",
    aliases: ["우에노역", "우에노", "ueno", "ueno station", "上野", "上野駅"],
    lat: 35.7141,
    lng: 139.7774,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:asakusa-station",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "아사쿠사역",
    en: "Asakusa Station",
    local: "浅草駅",
    aliases: [
      "아사쿠사역",
      "아사쿠사",
      "asakusa",
      "asakusa station",
      "浅草",
      "浅草駅",
    ],
    lat: 35.7108,
    lng: 139.7967,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:akihabara-station",
    kind: "poi",
    parentId: "geo:jp:tokyo:akihabara",
    ko: "아키하바라역",
    en: "Akihabara Station",
    local: "秋葉原駅",
    aliases: ["아키하바라역", "akihabara station", "秋葉原駅", "아키바역"],
    lat: 35.6984,
    lng: 139.7731,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:ginza-station",
    kind: "poi",
    parentId: "geo:jp:tokyo:ginza",
    ko: "긴자역",
    en: "Ginza Station",
    local: "銀座駅",
    aliases: ["긴자역", "ginza station", "銀座駅"],
    lat: 35.6717,
    lng: 139.7649,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:shinagawa-station",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "시나가와역",
    en: "Shinagawa Station",
    local: "品川駅",
    aliases: [
      "시나가와역",
      "시나가와",
      "shinagawa",
      "shinagawa station",
      "品川",
      "品川駅",
    ],
    lat: 35.6284,
    lng: 139.7387,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:harajuku-station",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "하라주쿠역",
    en: "Harajuku Station",
    local: "原宿駅",
    aliases: [
      "하라주쿠역",
      "하라주쿠",
      "harajuku",
      "harajuku station",
      "原宿",
      "原宿駅",
    ],
    lat: 35.6702,
    lng: 139.7026,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:roppongi-station",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "롯폰기역",
    en: "Roppongi Station",
    local: "六本木駅",
    aliases: [
      "롯폰기역",
      "롯폰기",
      "roppongi",
      "roppongi station",
      "六本木",
      "六本木駅",
    ],
    lat: 35.6627,
    lng: 139.731,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:odaiba",
    kind: "district",
    parentId: "geo:jp:tokyo",
    ko: "오다이바",
    en: "Odaiba",
    local: "お台場",
    aliases: ["odaiba", "오다이바", "お台場", "다이바", "daiba"],
    lat: 35.6293,
    lng: 139.7795,
    ...JP,
  },
  // ——— Osaka ———
  {
    id: "geo:jp:osaka:shin-osaka-station",
    kind: "poi",
    parentId: "geo:jp:osaka",
    ko: "신오사카역",
    en: "Shin-Osaka Station",
    local: "新大阪駅",
    aliases: [
      "신오사카역",
      "신오사카",
      "shin-osaka",
      "shin osaka",
      "신오사카 역",
      "新大阪",
      "新大阪駅",
    ],
    lat: 34.7335,
    lng: 135.5002,
    ...JP,
  },
  {
    id: "geo:jp:osaka:tennoji-station",
    kind: "poi",
    parentId: "geo:jp:osaka",
    ko: "텐노지역",
    en: "Tennoji Station",
    local: "天王寺駅",
    aliases: [
      "텐노지역",
      "텐노지",
      "tennoji",
      "tennoji station",
      "天王寺",
      "天王寺駅",
    ],
    lat: 34.6473,
    lng: 135.5139,
    ...JP,
  },
  {
    id: "geo:jp:osaka:shinsaibashi",
    kind: "district",
    parentId: "geo:jp:osaka",
    ko: "신사이바시",
    en: "Shinsaibashi",
    local: "心斎橋",
    aliases: ["shinsaibashi", "신사이바시", "心斎橋", "신사이바시역"],
    lat: 34.6748,
    lng: 135.5013,
    ...JP,
  },
  {
    id: "geo:jp:osaka:dotonbori",
    kind: "neighborhood",
    parentId: "geo:jp:osaka",
    ko: "도톤보리",
    en: "Dotonbori",
    local: "道頓堀",
    aliases: ["dotonbori", "도톤보리", "道頓堀", "도톤보리역"],
    lat: 34.6687,
    lng: 135.5013,
    ...JP,
  },
  // ——— Kyoto / Kansai ———
  {
    id: "geo:jp:kyoto:kyoto-station",
    kind: "poi",
    parentId: "geo:jp:kyoto",
    ko: "교토역",
    en: "Kyoto Station",
    local: "京都駅",
    aliases: ["교토역", "kyoto station", "京都駅", "교토 역"],
    lat: 34.9858,
    lng: 135.7588,
    ...JP,
  },
  {
    id: "geo:jp:kyoto:gion",
    kind: "neighborhood",
    parentId: "geo:jp:kyoto",
    ko: "기온",
    en: "Gion",
    local: "祇園",
    aliases: ["gion", "기온", "祇園"],
    lat: 35.0036,
    lng: 135.7786,
    ...JP,
  },
  {
    id: "geo:jp:kyoto:arashiyama",
    kind: "neighborhood",
    parentId: "geo:jp:kyoto",
    ko: "아라시야마",
    en: "Arashiyama",
    local: "嵐山",
    aliases: ["arashiyama", "아라시야마", "嵐山"],
    lat: 35.0094,
    lng: 135.6678,
    ...JP,
  },
  {
    id: "geo:jp:kyoto:fushimi-inari",
    kind: "poi",
    parentId: "geo:jp:kyoto",
    ko: "후시미 이나리",
    en: "Fushimi Inari",
    local: "伏見稲荷大社",
    aliases: [
      "fushimi inari",
      "후시미이나리",
      "후시미 이나리",
      "伏見稲荷",
      "이나리 신사",
    ],
    lat: 34.9671,
    lng: 135.7727,
    ...JP,
  },
  // ——— Other JP hubs ———
  {
    id: "geo:jp:fukuoka:hakata-station",
    kind: "poi",
    parentId: "geo:jp:fukuoka",
    ko: "하카타역",
    en: "Hakata Station",
    local: "博多駅",
    aliases: [
      "하카타역",
      "하카타",
      "hakata",
      "hakata station",
      "博多",
      "博多駅",
    ],
    lat: 33.5897,
    lng: 130.4207,
    ...JP,
  },
  {
    id: "geo:jp:fukuoka:tenjin",
    kind: "district",
    parentId: "geo:jp:fukuoka",
    ko: "텐진",
    en: "Tenjin",
    local: "天神",
    aliases: ["tenjin", "텐진", "天神", "텐진역"],
    lat: 33.5903,
    lng: 130.4016,
    ...JP,
  },
  {
    id: "geo:jp:nagoya:nagoya-station",
    kind: "poi",
    parentId: "geo:jp:nagoya",
    ko: "나고야역",
    en: "Nagoya Station",
    local: "名古屋駅",
    aliases: ["나고야역", "nagoya station", "名古屋駅"],
    lat: 35.1709,
    lng: 136.8815,
    ...JP,
  },
  {
    id: "geo:jp:yokohama:yokohama-station",
    kind: "poi",
    parentId: "geo:jp:yokohama",
    ko: "요코하마역",
    en: "Yokohama Station",
    local: "横浜駅",
    aliases: ["요코하마역", "yokohama station", "横浜駅"],
    lat: 35.4657,
    lng: 139.622,
    ...JP,
  },
  {
    id: "geo:jp:hokkaido:sapporo-station",
    kind: "poi",
    parentId: "geo:jp:hokkaido:sapporo",
    ko: "삿포로역",
    en: "Sapporo Station",
    local: "札幌駅",
    aliases: ["삿포로역", "sapporo station", "札幌駅"],
    lat: 43.0686,
    lng: 141.3508,
    ...JP,
  },
  {
    id: "geo:jp:nara:nara-station",
    kind: "poi",
    parentId: "geo:jp:nara",
    ko: "나라역",
    en: "Nara Station",
    local: "奈良駅",
    aliases: ["나라역", "nara station", "奈良駅"],
    lat: 34.6805,
    lng: 135.819,
    ...JP,
  },
  {
    id: "geo:jp:okinawa:naha-airport",
    kind: "poi",
    parentId: "geo:jp:okinawa",
    ko: "나하 공항",
    en: "Naha Airport",
    local: "那覇空港",
    aliases: ["naha airport", "나하공항", "나하 공항", "oka", "那覇空港"],
    lat: 26.1958,
    lng: 127.6458,
    ...JP,
  },
  // ——— Seoul ———
  {
    id: "geo:kr:seoul:seoul-station",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "서울역",
    en: "Seoul Station",
    local: "서울역",
    aliases: ["서울역", "seoul station", "서울 역"],
    lat: 37.5547,
    lng: 126.9707,
    ...KR,
  },
  {
    id: "geo:kr:seoul:gangnam-station",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "강남역",
    en: "Gangnam Station",
    local: "강남역",
    aliases: ["강남역", "강남", "gangnam", "gangnam station"],
    lat: 37.4979,
    lng: 127.0276,
    ...KR,
  },
  {
    id: "geo:kr:seoul:hongdae",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "홍대입구역",
    en: "Hongik University Station",
    local: "홍대입구역",
    aliases: [
      "홍대입구역",
      "홍대",
      "홍대입구",
      "hongdae",
      "hongik",
      "hongdae station",
    ],
    lat: 37.5572,
    lng: 126.9254,
    ...KR,
  },
  {
    id: "geo:kr:seoul:myeongdong",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "명동역",
    en: "Myeongdong Station",
    local: "명동역",
    aliases: ["명동역", "명동", "myeongdong", "myeong-dong", "myeongdong station"],
    lat: 37.5636,
    lng: 126.9866,
    ...KR,
  },
  {
    id: "geo:kr:seoul:jamsil-station",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "잠실역",
    en: "Jamsil Station",
    local: "잠실역",
    aliases: ["잠실역", "잠실", "jamsil", "jamsil station"],
    lat: 37.5133,
    lng: 127.1001,
    ...KR,
  },
  {
    id: "geo:kr:seoul:itaewon",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "이태원역",
    en: "Itaewon Station",
    local: "이태원역",
    aliases: ["이태원역", "이태원", "itaewon", "itaewon station"],
    lat: 37.5345,
    lng: 126.9946,
    ...KR,
  },
  {
    id: "geo:kr:seoul:dongdaemun",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "동대문역",
    en: "Dongdaemun Station",
    local: "동대문역",
    aliases: ["동대문역", "동대문", "dongdaemun", "dongdaemun station", "DDP"],
    lat: 37.5714,
    lng: 127.0095,
    ...KR,
  },
  {
    id: "geo:kr:seoul:yeouido",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "여의도역",
    en: "Yeouido Station",
    local: "여의도역",
    aliases: ["여의도역", "여의도", "yeouido", "yeouido station"],
    lat: 37.5216,
    lng: 126.9243,
    ...KR,
  },
  {
    id: "geo:kr:seoul:sinchon",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "신촌역",
    en: "Sinchon Station",
    local: "신촌역",
    aliases: ["신촌역", "신촌", "sinchon", "sinchon station"],
    lat: 37.5551,
    lng: 126.9369,
    ...KR,
  },
  {
    id: "geo:kr:seoul:apgujeong",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "압구정역",
    en: "Apgujeong Station",
    local: "압구정역",
    aliases: ["압구정역", "압구정", "apgujeong", "apgujeong station"],
    lat: 37.5274,
    lng: 127.0285,
    ...KR,
  },
  {
    id: "geo:kr:seoul:samseong",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "삼성역",
    en: "Samseong Station",
    local: "삼성역",
    aliases: ["삼성역", "samseong", "samseong station", "COEX", "코엑스"],
    lat: 37.5088,
    lng: 127.0632,
    ...KR,
  },
  {
    id: "geo:kr:seoul:express-bus-terminal",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "고속터미널역",
    en: "Express Bus Terminal Station",
    local: "고속터미널역",
    aliases: [
      "고속터미널역",
      "고속터미널",
      "express bus terminal",
      "서울고속버스터미널",
    ],
    lat: 37.5045,
    lng: 127.0048,
    ...KR,
  },
  {
    id: "geo:kr:seoul:gwanghwamun",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "광화문",
    en: "Gwanghwamun",
    local: "광화문",
    aliases: ["광화문", "gwanghwamun", "광화문역"],
    lat: 37.5716,
    lng: 126.9769,
    ...KR,
  },
  // ——— Busan / Jeju ———
  {
    id: "geo:kr:busan:seomyeon",
    kind: "poi",
    parentId: "geo:kr:busan",
    ko: "서면역",
    en: "Seomyeon Station",
    local: "서면역",
    aliases: ["서면역", "서면", "seomyeon", "seomyeon station"],
    lat: 35.1578,
    lng: 129.0595,
    ...KR,
  },
  {
    id: "geo:kr:busan:haeundae",
    kind: "poi",
    parentId: "geo:kr:busan",
    ko: "해운대역",
    en: "Haeundae Station",
    local: "해운대역",
    aliases: ["해운대역", "해운대", "haeundae", "haeundae station"],
    lat: 35.1631,
    lng: 129.1635,
    ...KR,
  },
  {
    id: "geo:kr:busan:busan-station",
    kind: "poi",
    parentId: "geo:kr:busan",
    ko: "부산역",
    en: "Busan Station",
    local: "부산역",
    aliases: ["부산역", "busan station"],
    lat: 35.1152,
    lng: 129.0415,
    ...KR,
  },
  {
    id: "geo:kr:busan:nampo",
    kind: "poi",
    parentId: "geo:kr:busan",
    ko: "남포역",
    en: "Nampo Station",
    local: "남포역",
    aliases: ["남포역", "남포동", "남포", "nampo", "nampodong"],
    lat: 35.0978,
    lng: 129.0305,
    ...KR,
  },
  {
    id: "geo:kr:jeju:jeju-airport",
    kind: "poi",
    parentId: "geo:kr:jeju",
    ko: "제주공항",
    en: "Jeju International Airport",
    local: "제주국제공항",
    aliases: ["제주공항", "제주 공항", "cje", "jeju airport"],
    lat: 33.5113,
    lng: 126.493,
    ...KR,
  },
];

/** Extra landmarks (travel ask frequency). */
const LANDMARK_ROWS: readonly FrequentGeoRow[] = [
  {
    id: "geo:jp:tokyo:tokyo-tower",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "도쿄타워",
    en: "Tokyo Tower",
    local: "東京タワー",
    aliases: ["tokyo tower", "도쿄타워", "도쿄 타워", "東京タワー"],
    lat: 35.6586,
    lng: 139.7454,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:meiji-shrine",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "메이지 신궁",
    en: "Meiji Shrine",
    local: "明治神宮",
    aliases: ["meiji shrine", "메이지신궁", "메이지 신궁", "明治神宮"],
    lat: 35.6764,
    lng: 139.6993,
    ...JP,
  },
  {
    id: "geo:jp:osaka:osaka-castle",
    kind: "poi",
    parentId: "geo:jp:osaka",
    ko: "오사카성",
    en: "Osaka Castle",
    local: "大阪城",
    aliases: ["osaka castle", "오사카성", "오사카 성", "大阪城"],
    lat: 34.6873,
    lng: 135.5262,
    ...JP,
  },
  {
    id: "geo:jp:tokyo:teamlab-planets",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    ko: "팀랩 플래닛",
    en: "teamLab Planets",
    local: "チームラボプラネッツ",
    aliases: [
      "teamlab planets",
      "팀랩 플래닛",
      "팀랩플래닛",
      "teamlab",
      "팀랩",
    ],
    lat: 35.649,
    lng: 139.7897,
    ...JP,
  },
  {
    id: "geo:kr:seoul:n-seoul-tower",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "N서울타워",
    en: "N Seoul Tower",
    local: "N서울타워",
    aliases: [
      "n서울타워",
      "남산타워",
      "남산서울타워",
      "n seoul tower",
      "namsan tower",
    ],
    lat: 37.5512,
    lng: 126.9882,
    ...KR,
  },
  {
    id: "geo:kr:seoul:gyeongbokgung",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "경복궁",
    en: "Gyeongbokgung",
    local: "경복궁",
    aliases: ["경복궁", "gyeongbokgung", "gyeongbok palace"],
    lat: 37.5796,
    lng: 126.977,
    ...KR,
  },
  {
    id: "geo:kr:seoul:lotte-world",
    kind: "poi",
    parentId: "geo:kr:seoul",
    ko: "롯데월드",
    en: "Lotte World",
    local: "롯데월드",
    aliases: ["롯데월드", "lotte world", "lotteworld"],
    lat: 37.511,
    lng: 127.098,
    ...KR,
  },
  {
    id: "geo:kr:busan:gamcheon",
    kind: "poi",
    parentId: "geo:kr:busan",
    ko: "감천문화마을",
    en: "Gamcheon Culture Village",
    local: "감천문화마을",
    aliases: ["감천문화마을", "감천", "gamcheon"],
    lat: 35.0975,
    lng: 129.0105,
    ...KR,
  },
];

export const FREQUENT_TRAVEL_GEO_NODES: readonly WorldGeoNode[] = [
  ...REGION_ROWS,
  ...STATION_ROWS,
  ...LANDMARK_ROWS,
].map(nodeFromRow);

/** Station-like POIs for Entity Resolver dictionary (geoId attached). */
export const FREQUENT_STATION_GEO_IDS: readonly WorldGeoEntityId[] =
  STATION_ROWS.filter(
    (row) =>
      row.kind === "poi" &&
      /역|station|駅|공항|airport|空港/iu.test(
        [row.ko, row.en, row.local, ...row.aliases].join(" "),
      ),
  ).map((row) => row.id);

export function listFrequentTravelGeoNodes(): readonly WorldGeoNode[] {
  return FREQUENT_TRAVEL_GEO_NODES;
}
